apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: app-ingress
  namespace: devops-dev
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  rules:
    # Frontend endpoint
    - host: app.devops-test.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80

    # Backend endpoint
    - host: api.devops-test.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port: 5000
          # - path: /backend2
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: backend2
          #       port:
          #         number: 8080
