apiVersion: v1
kind: Secret

metadata:
  name: app-secrets
  namespace: devops-dev

type: Opaque
stringData:
  DATABASE_URL: postgres://postgres:postgres-pass@postgres:5432/sampledb?schema=public
  DB_PASS: postgres-pass