apiVersion: v1
kind: Secret

metadata:
  name: backend-secrets
  namespace: devops-dev

type: Opaque
stringData:
  # DB_PASS: postgres-pass


apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret
  namespace: devops-dev
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres-pass
  POSTGRES_DB: sampledb