apiVersion: v1
kind: ConfigMap

metadata:
  name: app-config
  namespace: devops-dev

data:
  PORT: "5000"
  NODE_ENV: "production"
  API_VERSION: "v1"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "sampledb"
  DB_USER: "postgres"
